### PR TITLE
Report all errors/warnings from swipl/sicstus

### PR DESCRIPTION
**Pull request by jmanuel1**
This PR adds support for reporting multiple errors and/or warnings. (I haven't used linter-prolog in a while, so maybe this has already been fixed?)

### CODE REVIEW

**Comment by wysiib** [comment]
Thank you for your help. Sadly, I am not a regular Prolog-user myself anymore. Furthermore, this repository has bit-rotted a little and the CI has to be replaced.

Thus, it will take me a little time to check this PR.

**Comment by wysiib** [comment]
Can you rebase to master to see if your PR passes the Github Actions test pipeline?

**Comment by jmanuel1** [comment]
Done!

**Comment by wysiib** [comment]
Looking good and test are passing. I’ll prepare a new release later on. Thanks again!

**Pull request merged**
